name: CodeQL Analysis, Bandit Scan, and Debricked Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '23 18 * * 2'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write # Required for uploading SARIF files

jobs:
  analyze_codeql:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Step 3: Perform CodeQL Analysis and specify the output SARIF file location
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: .github/codeql/results.sarif  # This will generate the SARIF file in the specified path

      # Step 4: Upload CodeQL SARIF results with a unique category
      - name: Upload CodeQL SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .github/codeql/results.sarif # Upload the SARIF file generated in the previous step
          token: ${{ secrets.GITHUB_TOKEN }}
          category: codeql-analysis-unique-category # This makes the upload unique
          wait-for-processing: true

  bandit_scan:
    name: Bandit Python Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 5: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 6: Run Bandit Security Scan
      - name: Run Bandit Security Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          exit_zero: true
          path: "."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  debricked_scan:
    name: Debricked Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 7: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 8: Run Debricked Scan
      - name: Debricked Security Scan
        uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
