name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history for accurate analysis

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v4.0.0
      with:
        args: >
          -Dsonar.projectKey=Rupalsoni123_codeql-test
          -Dsonar.organization=rupalsoni123
          -Dsonar.host.url=https://sonarcloud.io # Replace with your SonarQube server URL if self-hosted
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
